### ISSUE TITLE
[1.16.5] Incompatiblity with Tiered (forge)

### ISSUE THREAD

**Issue by Cixon** [SuperMartijn642/DurabilityTooltip#1]
**Context:** Tiered doesn't display GUI infomation when installed with DurabilityTooltip

**Mod:** https://www.curseforge.com/minecraft/mc-mods/tiered-forge

**Comment by SuperMartijn642** [comment]
Durability Tooltip will show tooltips on other mods' items now in version 1.0.1.

Thanks for the report!

**Comment by Cixon** [comment]
> Durability Tooltip will show tooltips on other mods' items now in version 1.0.1.
> 
> Thanks for the report!

thank you!
