### ISSUE TITLE
[Bug] 1.19.2 flagged version expects 1.19.4

### ISSUE THREAD

**Issue by Dekamir** [SuperMartijn642/DurabilityTooltip#10]
**Version Info**
- Minecraft 1.19.2
- Fabric 0.14.19
- Fabric API 0.76.0
- Durability Tooltip 1.1.4

**Steps to Reproduce**
Install Durability Tooltip 1.1.4 to a Minecraft 1.19.2 Fabric instance.

**Screenshots**
![image](https://github.com/SuperMartijn642/DurabilityTooltip/assets/28929300/328940f9-4922-4555-9393-2d5f618c6d80)

**Comment by SuperMartijn642** [comment]
This has already been fixed, please update to the latest version.

**Comment by Dekamir** [comment]
The mod file 1.1.4a is not flagged as 1.19.2 on CurseForge, as it is only flagged as 1.19.4 compatible. CurseForge clients won't download the latest update.

**Comment by SuperMartijn642** [comment]
Ah I see what you mean, fixed now 👍

**Comment by sandstripes** [comment]
Same issue on modrinth

**Comment by SuperMartijn642** [comment]
Fixed!
