### ISSUE TITLE
[Bug] Possible issue with Iguana Tweaks Reborn

### ISSUE THREAD

**Issue by Maypul** [SuperMartijn642/DurabilityTooltip#13]
**Version Info**
- Minecraft, 1.19.2
- Durability Tooltip, 1.1.5 Forge

**Description of the Bug**
Sometimes, Durability tooltip displays wrong number. But the tools still breaks after newly set number. The only mod that changes durability of items in my pack is Iguana Tweaks Reborn, I set lower values for wooden and stone tools. I can not consistently reproduce it, but sometimes the tooltip seems to show default durability of tools instead of real value. It still counts use correcly, meaning -1, but does not break on 0 but after the new durability.

**Steps to Reproduce**
Have DurabilityTooltip installed with Iguana Tweaks Reborn with InsaneLib, have some tools changed in tool_durabilities.json
Then, try giving yourself this specific tool, also durability is visible in creative mode, sometimes it showed correct value, sometimes the old pre-change but still broke as the correct value.

**Screenshots**
![image](https://github.com/SuperMartijn642/DurabilityTooltip/assets/98578889/f73cb2fc-d084-4dd5-acba-ebec1eae0a55) (it would also always show this value if I disabled Iguana Tweaks)
should have 1 use as in:
![image](https://github.com/SuperMartijn642/DurabilityTooltip/assets/98578889/e8689083-640c-4c72-835c-6a50e4919e1c) 
Currently, on the server where it happened, it shows correct value and at the moment I can't reproduce it.

Factless theory: maybe mods does not always load in the same order and sometimes after server reboot it messes things up.

Client and server mods: https://pastebin.com/EsMQnjs9

**Comment by SuperMartijn642** [comment]
My guess here is that Iguana Tweaks Reborn isn't synching the durability changes to the client correctly. Durability Tooltip does nothing more than display the current damage of an item stack reports and the max damage an item stack reports.

**Comment by Maypul** [comment]
It appears to be known issue which was fixed in 1.19.4 and 1.20 versions, but not in 1.19.2
