### ISSUE TITLE
Game crashes when loading world

### ISSUE THREAD

**Issue by FoxySophie** [SuperMartijn642/DurabilityTooltip#14]
**Version Info**
Minecraft 1.19.2, Fabric 0.14.22
Durability Tooltip 1.1.5
SuperMartijn642's Config Lib 1.1.8

**Steps to Reproduce**
Install the current version of those mods. Start the game and try to load/join a world, game crashes as soon as the loading finishes.

**Crash report (~/logs/latest.log)**
[crash-2023-09-29_08.26.40-client.txt](https://github.com/SuperMartijn642/DurabilityTooltip/files/12761583/crash-2023-09-29_08.26.40-client.txt)

**Comment by SuperMartijn642** [comment]
Fixed now with the separate versions for 1.19.2 and 1.19.4.
Thank you for reporting the issue!
