### ISSUE TITLE
[Feature] Show durability for broken tools from Silent Gear

### ISSUE THREAD

**Issue by MagicSecret** [SuperMartijn642/DurabilityTooltip#17]
**Is your feature request related to a problem? Please describe.**
 
 I'm always frustrated when the durability is between 0 and 1 as silentgear shows it to be so, best bet is to use it's lore "You broke it!" for optimal correction

**Describe the solution you'd like**
I would want the durability to be shown for broken tools relating to silentgear such as silentgear:pickaxe, hammer, etc. To get the best result using the red colored text, "You broke it!" may be optimal to show the correct user oriented durability, since the durability can range from 0 to 1
![silentgear_example](https://github.com/SuperMartijn642/DurabilityTooltip/assets/29675778/fd8117c8-8cca-4b3a-8468-945deb3eff55)

**Comment by SuperMartijn642** [comment]
So does this only affect Silent Gear? In that case, you should probably request an option for this from them.
Adding integration to show the durability only when a tool is broken for one mod specifically seems rather odd. That sounds like it should just be part of that mod.
