### ISSUE TITLE
[Bug] No tooltip with advanced tooltips enabled and full durability

### ISSUE THREAD

**Issue by freopt** [SuperMartijn642/DurabilityTooltip#2]
**Version Info**
- Minecraft, 1.18.1
- Durability Tooltip, 1.0.1

**Description of the Bug**
The tooltip doesn't work when advanced tooltips are enabled and an item has full durability.

**Screenshots**
![image](https://user-images.githubusercontent.com/45438411/155859347-1417fb15-bfed-48d0-8f57-b28898fd5180.png)

vs other items

![image](https://user-images.githubusercontent.com/45438411/155859353-bbcebee7-06d2-4347-9737-bf83faf1aaf1.png)

**Comment by SuperMartijn642** [comment]
I fixed it now in Durability Tooltip 1.1.0.

Thank you for reporting the issue!
