### ISSUE TITLE
"Bug" - Mod isn't Client Side - Requires the Config Lib to function

### ISSUE THREAD

**Issue by PhweeDev** [SuperMartijn642/DurabilityTooltip#3]
Although it's not a bug, The mod will not work unless it has the Config Library. Which technically means it's not a Client Side mod, as the server requires the Config Lib to work without providing a "Mismatched mod list" error.

**Comment by SuperMartijn642** [comment]
Version 1.1.7 of my config library will now allow any connections as long as there are no config values which need to be synced, thus you should now be able to use it just client-side together with Durability Tooltip 👍
